name: pull_request_pipeline

on:
  pull_request:
    branches:
      - main
jobs:
  pull_request_pipeline:
    name: pull_request_pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: 18.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Install Dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Check Prettier
        run: npm run prettier-check

      - name: Run Tests
        run: npm test
